=== jaouad00/webservices/1.XML/persons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2022 rel. 2 (x64) (http://www.altova.com) by  (ABIS Training and Consulting) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://abis.be/persons" xmlns:base="http://abis.be/base" targetNamespace="http://abis.be/persons" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://abis.be/base" schemaLocation="base.xsd"/>
	<xs:element name="persons">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="lastName" type="base:max50Type"/>
				<xs:element name="firstName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:name"/>
				<xs:element name="age" type="xs:int"/>
				<xs:element ref="base:country"/>
				<xs:element name="accountNumber" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[A-Z]{2}[0-9]{2} [A-Z]{4} \d{10}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="nr" type="xs:int"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jaouad00/webservices/1.XML/persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://abis.be/persons persons.xsd" xmlns="http://abis.be/persons" xmlns:base="http://abis.be/base">
	<person nr="1">
		<name>
			<lastName>Schillebeeckx</lastName>
			<firstName>Sandy</firstName>
		</name>
		<age>42</age>
		<base:country countryCode="BE">Belgium</base:country>
	</person>
	<person nr="2">
		<name>
			<lastName>Uiterwijk</lastName>
			<firstName/>
		</name>
		<age>0</age>
		<base:country countryCode="NL">The Netherlands</base:country>
		<accountNumber>NL20 INGB 0001234567</accountNumber>
	</person>
</persons>
