=== jaouad00/webservices/Exercises/2.WebServices/ex2/course.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://abis.be/courses" xmlns:tns="http://abis.be/courses">
		<xs:element name="course">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="courseId" type="xs:string"/>
						<xs:element ref="tns:shortTitle" />
						<xs:element name="longTitle" type="xs:string"/>
						<xs:element ref="tns:numberOfDays"/>
						<xs:element name="pricePerDay" type="xs:double"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="numberOfDays" type="xs:int"/>
			<xs:element name="shortTitle" type="xs:string"/>
			
			<xs:element name="courses">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="tns:course" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
</xs:schema>

=== jaouad00/webservices/Exercises/2.WebServices/ex2/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2022 rel. 2 (x64) (http://www.altova.com)-->
<courses xmlns="http://abis.be/courses" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://abis.be/courses course.xsd">
	<course>
		<courseId>1</courseId>
		<shortTitle>SQLBAS</shortTitle>
		<longTitle>SQL Fundamentals</longTitle>
		<numberOfDays>2</numberOfDays>
		<pricePerDay>375.0</pricePerDay>
	</course>
	<course>
		<courseId>2</courseId>
		<shortTitle>SPRING</shortTitle>
		<longTitle>SPRING Fundamentals</longTitle>
		<numberOfDays>3</numberOfDays>
		<pricePerDay>450.0</pricePerDay>
	</course>
	<course>
		<courseId>3</courseId>
		<shortTitle>SPRINGREST</shortTitle>
		<longTitle>Building REST APIs with Spring Boot</longTitle>
		<numberOfDays>3</numberOfDays>
		<pricePerDay>500.0</pricePerDay>
	</course>
</courses>
