=== jaouad00/webservices/Exercises/1.XML/ex2/families.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="families">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="family" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="familyName" type="xs:string"/>
							<xs:element name="address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="street" type="xs:string"/>
										<xs:element name="nr" type="xs:string"/>
										<xs:element name="city" type="xs:string"/>
										<xs:element name="countryCode" type="xs:string"/>
									</xs:sequence>
									<xs:attribute name="zipcode" type="xs:string"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="members">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="member" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="firstName" type="xs:string"/>
																<xs:element name="lastName" type="xs:string"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="birthdate" type="xs:string"/>
													<xs:element name="gender" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="pets" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="pet" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="species" type="xs:string"/>
													<xs:element name="name" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jaouad00/webservices/Exercises/1.XML/ex5/families.xml
<?xml version="1.0" encoding="UTF-8"?>
<families xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://abis.be/families families.xsd" xmlns="http://abis.be/families" xmlns:a="http://abis.be/address">
	<family>
		<familyName>Van Buggenhout - Schillebeeckx</familyName>
		<a:address zipcode="3000">
			<a:street>Somestreet</a:street>
			<a:nr>1</a:nr>
			<a:city>Kessel-Lo</a:city>
			<a:countryCode>BE</a:countryCode>
		</a:address>
		<members>
			<member>
				<name>
					<firstName>Sandy</firstName>
					<lastName>Schillebeeckx</lastName>
				</name>
				<birthdate>10/04/1978</birthdate>
				<gender>F</gender>
			</member>
			<member>
				<name>
					<firstName>Kristoff</firstName>
					<lastName>Van Buggenhout</lastName>
				</name>
				<birthdate>22/11/1979</birthdate>
				<gender>M</gender>
			</member>
		</members>
	</family>
	<family>
		<familyName>Wijnants-Otten</familyName>
		<a:address zipcode="2300AB">
			<a:street>Somestreet</a:street>
			<a:nr>1</a:nr>
			<a:city>Turnhout</a:city>
			<a:countryCode>BE</a:countryCode>
		</a:address>
		<members>
			<member>
				<name>
					<firstName>Danny</firstName>
					<lastName>Wijnants</lastName>
				</name>
				<birthdate>18/01/1971</birthdate>
				<gender>M</gender>
			</member>
			<member>
				<name>
					<firstName>Peggy</firstName>
					<lastName>Otten</lastName>
				</name>
				<birthdate>06/06/1972</birthdate>
				<gender>F</gender>
			</member>
			<member>
				<name>
					<firstName>Robin</firstName>
					<lastName>Wijnants</lastName>
				</name>
				<birthdate>18/08/2000</birthdate>
				<gender>M</gender>
			</member>
			<member>
				<name>
					<firstName>Yoshin</firstName>
					<lastName>Wijnants</lastName>
				</name>
				<birthdate>04/09/2001</birthdate>
				<gender>M</gender>
			</member>
		</members>
		<pets>
			<pet>
				<species>dog</species>
				<name>Mona</name>
			</pet>
			<pet>
				<species>dog</species>
				<name>Hashi</name>
			</pet>
			<pet>
				<species>cat</species>
				<name>Felix</name>
			</pet>
		</pets>
	</family>
</families>

=== jaouad00/webservices/Exercises/1.XML/ex3/families.xml
<?xml version="1.0" encoding="UTF-8"?>
<families xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="www.abis.be/families file:///C:/Users/Duser/Desktop/SmalsJava/XMLandSoap/Exercises/1.XML/ex3/families.xsd" xmlns="www.abis.be/families" xmlns:a="www.abis.be/address">
	<family>
		<familyName>Van Buggenhout - Schillebeeckx</familyName>
		<a:address zipcode="3000">
			<a:street>Somestreet</a:street>
			<a:nr>1</a:nr>
			<a:city>Kessel-Lo</a:city>
			<a:countryCode>BE</a:countryCode>
		</a:address>
		<members>
			<member>
				<name>
					<a:firstName>Sandy</a:firstName>
					<a:lastName>Schillebeeckx</a:lastName>
				</name>
				<birthdate>10/04/1978</birthdate>
				<gender>F</gender>
			</member>
			<member>
				<name>
					<a:firstName>Kristoff</a:firstName>
					<a:lastName>Van Buggenhout</a:lastName>
				</name>
				<birthdate>22/11/1979</birthdate>
				<gender>M</gender>
			</member>
		</members>
	</family>
	<family>
		<familyName>Wijnants-Otten</familyName>
		<a:address zipcode="2300 AB">
			<a:street>Somestreet</a:street>
			<a:nr>1</a:nr>
			<a:city>Turnhout</a:city>
			<a:countryCode>BE</a:countryCode>
		</a:address>
		<members>
			<member>
				<name>
					<a:firstName>Danny</a:firstName>
					<a:lastName>Wijnants</a:lastName>
				</name>
				<birthdate>18/01/1971</birthdate>
				<gender>M</gender>
			</member>
			<member>
				<name>
					<a:firstName>Peggy</a:firstName>
					<a:lastName>Otten</a:lastName>
				</name>
				<birthdate>06/06/1972</birthdate>
				<gender>F</gender>
			</member>
			<member>
				<name>
					<a:firstName>Robin</a:firstName>
					<a:lastName>Wijnants</a:lastName>
				</name>
				<birthdate>18/08/2000</birthdate>
				<gender>M</gender>
			</member>
			<member>
				<name>
					<a:firstName>Yoshin</a:firstName>
					<a:lastName>Wijnants</a:lastName>
				</name>
				<birthdate>04/09/2001</birthdate>
				<gender>M</gender>
			</member>
		</members>
		<pets>
			<pet>
				<species>dog</species>
				<name>Mona</name>
			</pet>
			<pet>
				<species>dog</species>
				<name>Hashi</name>
			</pet>
			<pet>
				<species>cat</species>
				<name>Felix</name>
			</pet>
		</pets>
	</family>
</families>
